# Site settings
title: Wakanda AI
email: cmanouan@alumni.cmu.edu
description: Webpage of The Wakanda AI Project under AFRETEC
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  African Language Technologies Group<br/>
  <a href="https://engineering.cmu.edu/afretec/index.html" target="_blank">AFRETEC</a>

location: >
  Carnegie Mellon University Africa<br/>
  Regional ICT Center of Excellence Bldg<br/>
  Kigali Innovation City - Bumbogo<br/>
  BP 6150, Kigali, Rwanda<br/>

contact: >
  <a href="mailto:cmanouan@alumni.cmu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact us via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: team
  # - name: publications
  # - name: talks
  # - name: software
  - name: blogs
  - name: news

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
