- name: Wakanda AI
  photo: ALTGr.jpeg
  info: Engineering Advanced Technologies for African Mother Tongues
  email: cmanouan@alumni.cmu.edu
  github: https://github.com/wakandaai
  duration: 2024-2027