- name: Wakanda AI
  photo: ALTGr.jpeg
  info: Engineering Advanced Speech Technologies for African Languages
  email: cmanouan@alumni.cmu.edu
  github: https://github.com/wakandaai
  duration: 2024-2027